# Example from https://blog.rmhogervorst.nl/blog/2020/09/24/running-an-r-script-on-a-schedule-gitlab/

stages:
  - check_govs
  - git

before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends ${APT_PKGS}
  - export PATH="/usr/local/lib/R/site-library/littler/examples/:${PATH}"
  - echo "options(Ncpus = $(nproc --all))" >> /usr/local/lib/R/etc/Rprofile.site
  - R -e  'install.packages(c("dplyr","readr","diffdf","rvest","emayili"))'
  - mkdir -p ~/.local/share/renv
 # - R -e 'renv::restore()'
  
# setup steps
run:
  tags:
      - docker
  image: rocker/r-ver:4.0.4
  script:
      - Rscript scripts/list_council_website.R
  artifacts: 
      paths:
      - log/test.txt

check_govs:
  stage: check_govs
  script: echo 'Check Govs'

git:
 stage: git

 allow_failure: true
 
 variables:
  GIT_CLEAN_FLAGS: none
 
  before_script:
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh/
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - git config --global user.email "git-bot@ci.uni-due.de"
  - git config --global user.name "CI/CD Pipeline"
  - git remote set-url origin git@git.uni-due.de:sjsthaus/council_configurations.git

 script:
  - git add .
  - git commit -am "[skip ci] Check for new governments in place $(date +"%D")"
  - git push origin HEAD:master --force


