# Example from https://blog.rmhogervorst.nl/blog/2020/09/24/running-an-r-script-on-a-schedule-gitlab/

#stages:
#  - check_govs
#  - git

before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends ${APT_PKGS}
  - export PATH="/usr/local/lib/R/site-library/littler/examples/:${PATH}"
  - echo "options(Ncpus = $(nproc --all))" >> /usr/local/lib/R/etc/Rprofile.site
  - R -e  'install.packages(c("dplyr","readr","diffdf","xml2","rvest","emayili"))'
  - mkdir -p ~/.local/share/renv
 # - R -e 'renv::restore()'
  
# setup steps
run:
  tags:
      - docker
  image: rocker/r-ver:4.0.4
  script:
      - Rscript scripts/list_council_website.R
  artifacts: 
      paths:
      - log/test.txt
