---
title: "datawrangling_council_list"
author: "Stefan Haußner"
date: "9 2 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#library(tidyverse)
library(readr)
library(tidyr)
library(dplyr)
library(stringr)
library(ggplot2)
library(forcats)
library(scales)
```

```{r}
govmembers <- read_csv("../data/eu_gov_members_per_country.csv")
```

https://maximilian.schalch.de/2018/05/complete-list-of-european-special-characters/

```{r}
surname_pattern <- "[A-ZÄÀÁÂÃÅǍĄĂÆĀÇĆĈČĎĐÈÉÊËĚĘĖĒĜĢĞĤÌÍÎÏĪΙĮĴĶĹĺĻŁĽľĿÑŃŇŅÖÒÓÔÕŐØŒŔŘŚŜŞŠȘŤŢÞȚÜÙÚÛŰŨŲŮŪŴÝŸŶŹŽŻß]*[-'’[:blank:]]*[A-ZÄÀÁÂÃÅǍĄĂÆĀÇĆĈČĎĐÈÉÊËĚĘĖĒĜĢĞĤÌÍÎÏĪΙĮĴĶĹĺĻŁĽľĿÑŃŇŅÖÒÓÔÕŐØŒŔŘŚŜŞŠȘŤŢÞȚÜÙÚÛŰŨŲŮŪŴÝŸŶŹŽŻß]*[-'’[:blank:]]*[A-ZÄÀÁÂÃÅǍĄĂÆĀÇĆĆĈČĎĐÈÉÊËĚĘĖĒĜĢĞĤÌÍÎÏĪΙĮĴĶĹĺĻŁĽľĿÑŃŇŅÖÒÓÔÕŐØŒŔŘŚŜŞŠȘŤŢÞȚÜÙÚÛŰŨŲŮŪŴÝŸŶŹŽŻß]+$"

govmembers_gg <- govmembers %>% 
  mutate(gender = case_when(str_sub(name,1,2) == "Mr" ~ "m",
                            str_sub(name,1,2) == "Ms" ~ "f",
                            TRUE ~ NA_character_),
         surname = str_extract(name, pattern = surname_pattern),
         prename = name %>% 
           str_remove(pattern = "(Ms )|(Mr )|(DR. )") %>% 
           str_remove(pattern = surname) %>% 
           str_squish()) %>%
  group_by(country) %>% 
  count(gender) %>% 
  mutate(ratio = n/(sum(n)),
         country = factor(country))


lvls <- names(sort(table(govmembers_gg[govmembers_gg$gender == "m", "country"])))

ggplot(govmembers_gg)+
  geom_col(aes(x = country, y = ratio, fill = gender))+
  geom_hline(yintercept = 0.5)+
  coord_flip()+
  scale_y_continuous(labels = percent_format())
ggsave("../output/gfx/gender_balance_EUgovs.png", width = 13, height = 9)
```

